### ISSUE TITLE
Update Typ

### ISSUE THREAD

**Issue by Jerome2103** [joshuabeny1999/telegram-server-update-bot#3]
Show the type of update (whether it is security or normal).
Security updates, highlight them in color if possible.

**Comment by joshuabeny1999** [comment]
Hi @Jerome2103 

Thanks for requesting the feature request. I just released a new version (https://github.com/joshuabeny1999/telegram-server-update-bot/releases/tag/v1.0.0) wich now shows if a package is an security upgrade or not. 


Kind regards,
Joshua

Pull Request; #4
