### ISSUE TITLE
Pfad der Config

### ISSUE THREAD

**Issue by Jerome2103** [joshuabeny1999/telegram-server-update-bot#5]
Der default Path der Config ist "$HOME/.telegram-server-update-bot.yaml"
Bitte so integrieren das er auch im aktuellen Verzeichnis überprüft.

Zurzeit lautet mein Cronjob:
`0 18 * * * /scripts/ServerBot/telegram-server-update-bot update-check --config /scripts/ServerBot/.telegram-server-update-bot.yaml`

Schön wäre wenn ich auch nicht im $HOME bin, das ich dies reicht:
`0 18 * * * /scripts/ServerBot/telegram-server-update-bot update-check`

**Comment by joshuabeny1999** [comment]
#12 should Fix this issue.
