### ISSUE TITLE
Parameter Version

### ISSUE THREAD

**Issue by Jerome2103** [joshuabeny1999/telegram-server-update-bot#6]
Mit dem Parameter `-v` die Version ausgeben.

**Comment by Jerome2103** [comment]
Siehe 
#11 
#10

**Comment by joshuabeny1999** [comment]
Thanks for you help. I build it up from scratch. Your tried to solve it, that the version will be sent via telegram. But I think it is much better if the version is shown directly. I found also a way to get the version from the https://github.com/goreleaser/goreleaser, which i use to build the package. So i do not need to manually put the version inside. This could be forgotten. I implemented for that the Package https://github.com/christopherhein/go-version

A simple solution is not always the best. And I love to do it a bit more complicated 😉 

See my pull request for how I resolved it: #13
